# Todos direitos autorais reservados pelo QOTA.

name: Qota OCR Service CI - Lint & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ocr-ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'

      - name: Install System Dependencies (Tesseract & Poppler)
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils

      - name: Install Python Dependencies
        run: pip install -r requirements.txt
      
      - name: Download spaCy Model

        run: python -m spacy download pt_core_news_lg

      - name: Run Linter (Flake8)
        run: |
          # Instala o linter
          pip install flake8
          # Executa o linter
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Unit & Integration Tests (Pytest)
        run: |
          pytest